INSERT INTO `Club` (`Name`) VALUES('real madrid');
INSERT INTO `Club` (`Name`) VALUES('fc barcelona');
INSERT INTO `Club` (`Name`) VALUES('chelsea');
INSERT INTO `Club` (`Name`) VALUES('icons');
INSERT INTO `Club` (`Name`) VALUES('juventus');
INSERT INTO `Club` (`Name`) VALUES('paris saint-germain');
INSERT INTO `Club` (`Name`) VALUES('atlético madrid');
INSERT INTO `Club` (`Name`) VALUES('liverpool');
INSERT INTO `Club` (`Name`) VALUES('fc bayern münchen');
INSERT INTO `Club` (`Name`) VALUES('manchester united');
INSERT INTO `Club` (`Name`) VALUES('manchester city');
INSERT INTO `Club` (`Name`) VALUES('milan');
INSERT INTO `Club` (`Name`) VALUES('tottenham hotspur');
INSERT INTO `Club` (`Name`) VALUES('borussia dortmund');
INSERT INTO `Club` (`Name`) VALUES('la galaxy');
INSERT INTO `Club` (`Name`) VALUES('napoli');
INSERT INTO `Club` (`Name`) VALUES('lazio');
INSERT INTO `Club` (`Name`) VALUES('roma');
INSERT INTO `Club` (`Name`) VALUES('fc porto');
INSERT INTO `Club` (`Name`) VALUES('boca juniors');
INSERT INTO `Club` (`Name`) VALUES('inter');
INSERT INTO `Club` (`Name`) VALUES('olympique lyonnais');
INSERT INTO `Club` (`Name`) VALUES('rb leipzig');
INSERT INTO `Club` (`Name`) VALUES('olympique de marseille');
INSERT INTO `Club` (`Name`) VALUES('aston villa');
INSERT INTO `Club` (`Name`) VALUES('feyenoord');
INSERT INTO `Club` (`Name`) VALUES('as monaco football club sa');
INSERT INTO `Club` (`Name`) VALUES('sl benfica');
INSERT INTO `Club` (`Name`) VALUES('sport-club freiburg');
INSERT INTO `Club` (`Name`) VALUES('valencia cf');
INSERT INTO `Club` (`Name`) VALUES('spartak moscow');
INSERT INTO `Club` (`Name`) VALUES('fc krasnodar');
INSERT INTO `Club` (`Name`) VALUES('colorado rapids');
INSERT INTO `Club` (`Name`) VALUES('arsenal');
INSERT INTO `Club` (`Name`) VALUES('club brugge kv');
INSERT INTO `Club` (`Name`) VALUES('new york city fc');
INSERT INTO `Club` (`Name`) VALUES('psv');
INSERT INTO `Club` (`Name`) VALUES('eintracht frankfurt');
INSERT INTO `Club` (`Name`) VALUES('tsg 1899 hoffenheim');
INSERT INTO `Club` (`Name`) VALUES('montpellier hérault sc');
INSERT INTO `Club` (`Name`) VALUES('fc schalke 04');
INSERT INTO `Club` (`Name`) VALUES('bayer 04 leverkusen');
INSERT INTO `Club` (`Name`) VALUES('shakhtar donetsk');
INSERT INTO `Club` (`Name`) VALUES('beşiktaş jk');
INSERT INTO `Club` (`Name`) VALUES('rc celta');
INSERT INTO `Club` (`Name`) VALUES('ajax');
INSERT INTO `Club` (`Name`) VALUES('trabzonspor');
INSERT INTO `Club` (`Name`) VALUES('orlando city soccer club');
INSERT INTO `Club` (`Name`) VALUES('galatasaray sk');
INSERT INTO `Club` (`Name`) VALUES('everton');
INSERT INTO `Club` (`Name`) VALUES('seattle sounders fc');
INSERT INTO `Club` (`Name`) VALUES('real betis');
INSERT INTO `Club` (`Name`) VALUES('sporting cp');
INSERT INTO `Club` (`Name`) VALUES('angers sco');
INSERT INTO `Club` (`Name`) VALUES('atalanta');
INSERT INTO `Club` (`Name`) VALUES('monterrey');
INSERT INTO `Club` (`Name`) VALUES('hannover 96');
INSERT INTO `Club` (`Name`) VALUES('sv werder bremen');
INSERT INTO `Club` (`Name`) VALUES('leicester city');
INSERT INTO `Club` (`Name`) VALUES('santos laguna');
INSERT INTO `Club` (`Name`) VALUES('as saint-étienne');
INSERT INTO `Club` (`Name`) VALUES('toronto fc');
INSERT INTO `Club` (`Name`) VALUES('cska moscow');
INSERT INTO `Club` (`Name`) VALUES('fc augsburg');
INSERT INTO `Club` (`Name`) VALUES('zenit st. petersburg');
INSERT INTO `Club` (`Name`) VALUES('medipol başakşehir fk');
INSERT INTO `Club` (`Name`) VALUES('vfb stuttgart');
INSERT INTO `Club` (`Name`) VALUES('sd eibar');
INSERT INTO `Club` (`Name`) VALUES('az');
INSERT INTO `Club` (`Name`) VALUES('sampdoria');
INSERT INTO `Club` (`Name`) VALUES('fiorentina');
INSERT INTO `Club` (`Name`) VALUES('west ham united');
INSERT INTO `Club` (`Name`) VALUES('stoke city');
INSERT INTO `Club` (`Name`) VALUES('monarcas morelia');
INSERT INTO `Club` (`Name`) VALUES('villarreal cf');
INSERT INTO `Club` (`Name`) VALUES('fc girondins de bordeaux');
INSERT INTO `Club` (`Name`) VALUES('vissel kobe');
INSERT INTO `Club` (`Name`) VALUES('wolverhampton wanderers');
INSERT INTO `Club` (`Name`) VALUES('kv kortrijk');
INSERT INTO `Club` (`Name`) VALUES('lokomotiv moscow');
INSERT INTO `Club` (`Name`) VALUES('chicago fire soccer club');
INSERT INTO `Club` (`Name`) VALUES('club león');
INSERT INTO `Club` (`Name`) VALUES('crystal palace');
INSERT INTO `Club` (`Name`) VALUES('west bromwich albion');
INSERT INTO `Club` (`Name`) VALUES('bsc young boys');
INSERT INTO `Club` (`Name`) VALUES('genoa');
INSERT INTO `Club` (`Name`) VALUES('standard de liège');
INSERT INTO `Club` (`Name`) VALUES('portland timbers');
INSERT INTO `Club` (`Name`) VALUES('fc red bull salzburg');
INSERT INTO `Club` (`Name`) VALUES('daegu fc');
INSERT INTO `Club` (`Name`) VALUES('sassuolo');
INSERT INTO `Club` (`Name`) VALUES('fulham');
INSERT INTO `Club` (`Name`) VALUES('kayserispor');
INSERT INTO `Club` (`Name`) VALUES('al ittihad');
INSERT INTO `Club` (`Name`) VALUES('watford');
INSERT INTO `Club` (`Name`) VALUES('al ahli');
INSERT INTO `Club` (`Name`) VALUES('burnley');
INSERT INTO `Club` (`Name`) VALUES('racing club');
INSERT INTO `Club` (`Name`) VALUES('sevilla fc');
INSERT INTO `Club` (`Name`) VALUES('jeonbuk hyundai motors');
INSERT INTO `Club` (`Name`) VALUES('tigres u.a.n.l.');
INSERT INTO `Club` (`Name`) VALUES('paok');
INSERT INTO `Club` (`Name`) VALUES('southampton');
INSERT INTO `Club` (`Name`) VALUES('fenerbahçe sk');
INSERT INTO `Club` (`Name`) VALUES('al taawoun');
INSERT INTO `Club` (`Name`) VALUES('1. fc köln');
INSERT INTO `Club` (`Name`) VALUES('randers fc');
INSERT INTO `Club` (`Name`) VALUES('al hilal');
INSERT INTO `Club` (`Name`) VALUES('u.n.a.m.');
INSERT INTO `Club` (`Name`) VALUES('rsc anderlecht');
INSERT INTO `Club` (`Name`) VALUES('ogc nice');
INSERT INTO `Club` (`Name`) VALUES('norwich city');
INSERT INTO `Club` (`Name`) VALUES('kawasaki frontale');
INSERT INTO `Club` (`Name`) VALUES('sydney fc');
INSERT INTO `Club` (`Name`) VALUES('atlanta united');
INSERT INTO `Club` (`Name`) VALUES('wigan athletic');
INSERT INTO `Club` (`Name`) VALUES('royal antwerp fc');
INSERT INTO `Club` (`Name`) VALUES('gamba osaka');
INSERT INTO `Club` (`Name`) VALUES('blackburn rovers');
INSERT INTO `Club` (`Name`) VALUES('torino');
INSERT INTO `Club` (`Name`) VALUES('nîmes olympique');
INSERT INTO `Club` (`Name`) VALUES('impact montréal');
INSERT INTO `Club` (`Name`) VALUES('bristol city');
INSERT INTO `Club` (`Name`) VALUES('derby county');
INSERT INTO `Club` (`Name`) VALUES('athletic club');
INSERT INTO `Club` (`Name`) VALUES('hertha bsc');
INSERT INTO `Club` (`Name`) VALUES('pachuca');
INSERT INTO `Club` (`Name`) VALUES('real sociedad');
INSERT INTO `Club` (`Name`) VALUES('malmö ff');
INSERT INTO `Club` (`Name`) VALUES('al faisaly');
INSERT INTO `Club` (`Name`) VALUES('fc nordsjælland');
INSERT INTO `Club` (`Name`) VALUES('los angeles football club');
INSERT INTO `Club` (`Name`) VALUES('rc deportivo');
INSERT INTO `Club` (`Name`) VALUES('portsmouth');
INSERT INTO `Club` (`Name`) VALUES('empoli');
INSERT INTO `Club` (`Name`) VALUES('fc basel');
INSERT INTO `Club` (`Name`) VALUES('hamburger sv');
INSERT INTO `Club` (`Name`) VALUES('bournemouth');
INSERT INTO `Club` (`Name`) VALUES('querétaro');
INSERT INTO `Club` (`Name`) VALUES('peterborough united');
INSERT INTO `Club` (`Name`) VALUES('sc braga');
INSERT INTO `Club` (`Name`) VALUES('fc københavn');
INSERT INTO `Club` (`Name`) VALUES('fc nantes');
INSERT INTO `Club` (`Name`) VALUES('rc strasbourg alsace');
INSERT INTO `Club` (`Name`) VALUES('wisła kraków');
INSERT INTO `Club` (`Name`) VALUES('cruz azul');
INSERT INTO `Club` (`Name`) VALUES('brøndby if');
INSERT INTO `Club` (`Name`) VALUES('rcd espanyol');
INSERT INTO `Club` (`Name`) VALUES('ud las palmas');
INSERT INTO `Club` (`Name`) VALUES('san lorenzo de almagro');
INSERT INTO `Club` (`Name`) VALUES('swansea city');
INSERT INTO `Club` (`Name`) VALUES('plymouth argyle');
INSERT INTO `Club` (`Name`) VALUES('reading');
INSERT INTO `Club` (`Name`) VALUES('kashiwa reysol');
INSERT INTO `Club` (`Name`) VALUES('vfl wolfsburg');
INSERT INTO `Club` (`Name`) VALUES('antalyaspor');
INSERT INTO `Club` (`Name`) VALUES('chievo verona');
INSERT INTO `Club` (`Name`) VALUES('1. fsv mainz 05');
INSERT INTO `Club` (`Name`) VALUES('alanyaspor');
INSERT INTO `Club` (`Name`) VALUES('rosenborg bk');
INSERT INTO `Club` (`Name`) VALUES('middlesbrough');
INSERT INTO `Club` (`Name`) VALUES('newcastle united');
INSERT INTO `Club` (`Name`) VALUES('krc genk');
INSERT INTO `Club` (`Name`) VALUES('preston north end');
INSERT INTO `Club` (`Name`) VALUES('brighton & hove albion');
INSERT INTO `Club` (`Name`) VALUES('fc dallas');
INSERT INTO `Club` (`Name`) VALUES('bologna');
INSERT INTO `Club` (`Name`) VALUES('stade rennais fc');
INSERT INTO `Club` (`Name`) VALUES('fc midtjylland');
INSERT INTO `Club` (`Name`) VALUES('parma');
INSERT INTO `Club` (`Name`) VALUES('cardiff city');
INSERT INTO `Club` (`Name`) VALUES('sv zulte-waregem');
INSERT INTO `Club` (`Name`) VALUES('rayo vallecano');
INSERT INTO `Club` (`Name`) VALUES('losc lille');
INSERT INTO `Club` (`Name`) VALUES('celtic');
INSERT INTO `Club` (`Name`) VALUES('cd leganés');
INSERT INTO `Club` (`Name`) VALUES('perth glory');
INSERT INTO `Club` (`Name`) VALUES('fc ufa');
INSERT INTO `Club` (`Name`) VALUES('new york red bulls');
INSERT INTO `Club` (`Name`) VALUES('olympiacos cfp');
INSERT INTO `Club` (`Name`) VALUES('d. alavés');
INSERT INTO `Club` (`Name`) VALUES('málaga cf');
INSERT INTO `Club` (`Name`) VALUES('américa de cali');
INSERT INTO `Club` (`Name`) VALUES('hull city');
INSERT INTO `Club` (`Name`) VALUES('göztepe sk');
INSERT INTO `Club` (`Name`) VALUES('kaizer chiefs');
INSERT INTO `Club` (`Name`) VALUES('osmanlıspor');
INSERT INTO `Club` (`Name`) VALUES('fc utrecht');
INSERT INTO `Club` (`Name`) VALUES('spal');
INSERT INTO `Club` (`Name`) VALUES('en avant de guingamp');
INSERT INTO `Club` (`Name`) VALUES('san jose earthquakes');
INSERT INTO `Club` (`Name`) VALUES('toulouse football club');
INSERT INTO `Club` (`Name`) VALUES('guadalajara');
INSERT INTO `Club` (`Name`) VALUES('club atlético huracán');
INSERT INTO `Club` (`Name`) VALUES('córdoba cf');
INSERT INTO `Club` (`Name`) VALUES('philadelphia union');
INSERT INTO `Club` (`Name`) VALUES('suwon samsung bluewings');
INSERT INTO `Club` (`Name`) VALUES('club tijuana');
INSERT INTO `Club` (`Name`) VALUES('fc twente');
INSERT INTO `Club` (`Name`) VALUES('shrewsbury');
INSERT INTO `Club` (`Name`) VALUES('sagan tosu');
INSERT INTO `Club` (`Name`) VALUES('holstein kiel');
INSERT INTO `Club` (`Name`) VALUES('sc paderborn 07');
INSERT INTO `Club` (`Name`) VALUES('aik');
INSERT INTO `Club` (`Name`) VALUES('d.c. united');
INSERT INTO `Club` (`Name`) VALUES('river plate');
INSERT INTO `Club` (`Name`) VALUES('melbourne victory');
INSERT INTO `Club` (`Name`) VALUES('levante ud');
INSERT INTO `Club` (`Name`) VALUES('estac troyes');
INSERT INTO `Club` (`Name`) VALUES('aek athens');
INSERT INTO `Club` (`Name`) VALUES('independiente');
INSERT INTO `Club` (`Name`) VALUES('deportivo toluca');
INSERT INTO `Club` (`Name`) VALUES('vancouver whitecaps fc');
INSERT INTO `Club` (`Name`) VALUES('club américa');
INSERT INTO `Club` (`Name`) VALUES('akhisar belediyespor');
INSERT INTO `Club` (`Name`) VALUES('coventry city');
INSERT INTO `Club` (`Name`) VALUES('sparta praha');
INSERT INTO `Club` (`Name`) VALUES('udinese');
INSERT INTO `Club` (`Name`) VALUES('getafe cf');
INSERT INTO `Club` (`Name`) VALUES('club atlético lanús');
INSERT INTO `Club` (`Name`) VALUES('rangers fc');
INSERT INTO `Club` (`Name`) VALUES('dijon fco');
INSERT INTO `Club` (`Name`) VALUES('legia warszawa');
INSERT INTO `Club` (`Name`) VALUES('vitória setúbal');
INSERT INTO `Club` (`Name`) VALUES('fk austria wien');
INSERT INTO `Club` (`Name`) VALUES('football club de metz');
INSERT INTO `Club` (`Name`) VALUES('vila das aves');
INSERT INTO `Club` (`Name`) VALUES('rubin kazan');
INSERT INTO `Club` (`Name`) VALUES('fc arsenal tula');
INSERT INTO `Club` (`Name`) VALUES('nàstic');
INSERT INTO `Club` (`Name`) VALUES('fc lorient');
INSERT INTO `Club` (`Name`) VALUES('accrington stanley');
INSERT INTO `Club` (`Name`) VALUES('sunderland');
INSERT INTO `Club` (`Name`) VALUES('vfl bochum 1848');
INSERT INTO `Club` (`Name`) VALUES('millonarios fc');
INSERT INTO `Club` (`Name`) VALUES('independiente santa fe');
INSERT INTO `Club` (`Name`) VALUES('urawa red diamonds');
INSERT INTO `Club` (`Name`) VALUES('girona fc');
INSERT INTO `Club` (`Name`) VALUES('r. valladolid cf');
INSERT INTO `Club` (`Name`) VALUES('panathinaikos fc');
INSERT INTO `Club` (`Name`) VALUES('vitória guimarães');
INSERT INTO `Club` (`Name`) VALUES('minnesota united fc');
INSERT INTO `Club` (`Name`) VALUES('wycombe wanderers');
INSERT INTO `Club` (`Name`) VALUES('club necaxa');
INSERT INTO `Club` (`Name`) VALUES('bursaspor');
INSERT INTO `Club` (`Name`) VALUES('benevento');
INSERT INTO `Club` (`Name`) VALUES('kv oostende');
INSERT INTO `Club` (`Name`) VALUES('rosario central');
INSERT INTO `Club` (`Name`) VALUES('granada cf');
INSERT INTO `Club` (`Name`) VALUES('junior fc');
INSERT INTO `Club` (`Name`) VALUES('columbus crew sc');
INSERT INTO `Club` (`Name`) VALUES('melbourne city');
INSERT INTO `Club` (`Name`) VALUES('cesena');
INSERT INTO `Club` (`Name`) VALUES('as nancy lorraine');
INSERT INTO `Club` (`Name`) VALUES('deportivo cali');
INSERT INTO `Club` (`Name`) VALUES('aberdeen');
INSERT INTO `Club` (`Name`) VALUES('luton town');
INSERT INTO `Club` (`Name`) VALUES('kaa gent');
INSERT INTO `Club` (`Name`) VALUES('argentinos juniors');
INSERT INTO `Club` (`Name`) VALUES('crotone');
INSERT INTO `Club` (`Name`) VALUES('vfr aalen');
INSERT INTO `Club` (`Name`) VALUES('vitesse');
INSERT INTO `Club` (`Name`) VALUES('fc st. pauli');
INSERT INTO `Club` (`Name`) VALUES('kv mechelen');
INSERT INTO `Club` (`Name`) VALUES('palermo');
INSERT INTO `Club` (`Name`) VALUES('kas eupen');
INSERT INTO `Club` (`Name`) VALUES('leeds united');
INSERT INTO `Club` (`Name`) VALUES('cagliari');
INSERT INTO `Club` (`Name`) VALUES('waasland-beveren');
INSERT INTO `Club` (`Name`) VALUES('evkur yeni malatyaspor');
INSERT INTO `Club` (`Name`) VALUES('colón de santa fe');
INSERT INTO `Club` (`Name`) VALUES('sk rapid wien');
INSERT INTO `Club` (`Name`) VALUES('frosinone');
INSERT INTO `Club` (`Name`) VALUES('sd huesca');
INSERT INTO `Club` (`Name`) VALUES('kardemir karabükspor');
INSERT INTO `Club` (`Name`) VALUES('r. sporting');
INSERT INTO `Club` (`Name`) VALUES('ca osasuna');
INSERT INTO `Club` (`Name`) VALUES('kasimpaşa sk');
INSERT INTO `Club` (`Name`) VALUES('sporting kansas city');
INSERT INTO `Club` (`Name`) VALUES('fortuna düsseldorf');
INSERT INTO `Club` (`Name`) VALUES('grasshopper club zürich');
INSERT INTO `Club` (`Name`) VALUES('djurgårdens if');
INSERT INTO `Club` (`Name`) VALUES('fc st. gallen');
INSERT INTO `Club` (`Name`) VALUES('estudiantes de la plata');
INSERT INTO `Club` (`Name`) VALUES('stade malherbe caen');
INSERT INTO `Club` (`Name`) VALUES('hellas verona');
INSERT INTO `Club` (`Name`) VALUES('rio ave fc');
INSERT INTO `Club` (`Name`) VALUES('independiente medellín');
INSERT INTO `Club` (`Name`) VALUES('atlético nacional');
INSERT INTO `Club` (`Name`) VALUES('vélez sarsfield');
INSERT INTO `Club` (`Name`) VALUES('bolton wanderers');
INSERT INTO `Club` (`Name`) VALUES('sivasspor');
INSERT INTO `Club` (`Name`) VALUES('spvgg unterhaching');
INSERT INTO `Club` (`Name`) VALUES('vvv-venlo');
INSERT INTO `Club` (`Name`) VALUES('cd lugo');
INSERT INTO `Club` (`Name`) VALUES('gençlerbirliği sk');
INSERT INTO `Club` (`Name`) VALUES('pogoń szczecin');
INSERT INTO `Club` (`Name`) VALUES('spvgg greuther fuerth');
INSERT INTO `Club` (`Name`) VALUES('deportes tolima');
INSERT INTO `Club` (`Name`) VALUES('walsall');
INSERT INTO `Club` (`Name`) VALUES('fc tosno');
INSERT INTO `Club` (`Name`) VALUES('al qadisiyah');
INSERT INTO `Club` (`Name`) VALUES('r. zaragoza');
INSERT INTO `Club` (`Name`) VALUES('ifk norrköping');
INSERT INTO `Club` (`Name`) VALUES('cheltenham town');
INSERT INTO `Club` (`Name`) VALUES('tromsø il');
INSERT INTO `Club` (`Name`) VALUES('ternana');
INSERT INTO `Club` (`Name`) VALUES('portimão');
INSERT INTO `Club` (`Name`) VALUES('kashima antlers');
INSERT INTO `Club` (`Name`) VALUES('1. fc nürnberg');
INSERT INTO `Club` (`Name`) VALUES('fc zürich');
INSERT INTO `Club` (`Name`) VALUES('willem ii');
INSERT INTO `Club` (`Name`) VALUES('santos');
INSERT INTO `Club` (`Name`) VALUES('pescara');
INSERT INTO `Club` (`Name`) VALUES('stade de reims');
INSERT INTO `Club` (`Name`) VALUES('tigres fc');
INSERT INTO `Club` (`Name`) VALUES('sc preußen münster');
INSERT INTO `Club` (`Name`) VALUES('sv meppen');
INSERT INTO `Club` (`Name`) VALUES('strømsgodset if');
INSERT INTO `Club` (`Name`) VALUES('sv wehen-wiesbaden');
INSERT INTO `Club` (`Name`) VALUES('notts county');
INSERT INTO `Club` (`Name`) VALUES('hokkaido consadole sapporo');
INSERT INTO `Club` (`Name`) VALUES('wellington phoenix');
INSERT INTO `Club` (`Name`) VALUES('brescia');
INSERT INTO `Club` (`Name`) VALUES('club atlético banfield');
INSERT INTO `Club` (`Name`) VALUES('western sydney wanderers');
INSERT INTO `Club` (`Name`) VALUES('fc ingolstadt 04');
INSERT INTO `Club` (`Name`) VALUES('amiens sc');
INSERT INTO `Club` (`Name`) VALUES('club atlas');
INSERT INTO `Club` (`Name`) VALUES('dinamo moscow');
INSERT INTO `Club` (`Name`) VALUES('fc groningen');
INSERT INTO `Club` (`Name`) VALUES('chaves');
INSERT INTO `Club` (`Name`) VALUES('cerezo osaka');
INSERT INTO `Club` (`Name`) VALUES('sv darmstadt 98');
INSERT INTO `Club` (`Name`) VALUES('cs marítimo');
INSERT INTO `Club` (`Name`) VALUES('st. johnstone fc');
INSERT INTO `Club` (`Name`) VALUES('lobos b.u.a.p.');
INSERT INTO `Club` (`Name`) VALUES('rotherham united');
INSERT INTO `Club` (`Name`) VALUES('r. oviedo');
INSERT INTO `Club` (`Name`) VALUES('cd huachipato');
INSERT INTO `Club` (`Name`) VALUES('la equidad');
INSERT INTO `Club` (`Name`) VALUES('ik sirius');
INSERT INTO `Club` (`Name`) VALUES('sg dynamo dresden');
INSERT INTO `Club` (`Name`) VALUES('havre athletic club');
INSERT INTO `Club` (`Name`) VALUES('sk sturm graz');
INSERT INTO `Club` (`Name`) VALUES('1. fc union berlin');
INSERT INTO `Club` (`Name`) VALUES('fc erzgebirge aue');
INSERT INTO `Club` (`Name`) VALUES('brisbane roar');
INSERT INTO `Club` (`Name`) VALUES('universidad de chile');
INSERT INTO `Club` (`Name`) VALUES('sc heerenveen');
INSERT INTO `Club` (`Name`) VALUES('bari');
INSERT INTO `Club` (`Name`) VALUES('athlétic club ajaccio');
INSERT INTO `Club` (`Name`) VALUES('fc rostov');
INSERT INTO `Club` (`Name`) VALUES('akhmat grozny');
INSERT INTO `Club` (`Name`) VALUES('kalmar ff');
INSERT INTO `Club` (`Name`) VALUES('sheffield wednesday');
INSERT INTO `Club` (`Name`) VALUES('puebla');
INSERT INTO `Club` (`Name`) VALUES('new england revolution');
INSERT INTO `Club` (`Name`) VALUES('fc seoul');
INSERT INTO `Club` (`Name`) VALUES('club atlético tigre');
INSERT INTO `Club` (`Name`) VALUES('belgrano de córdoba');
INSERT INTO `Club` (`Name`) VALUES('cd tenerife');
INSERT INTO `Club` (`Name`) VALUES('fc paços de ferreira');
INSERT INTO `Club` (`Name`) VALUES('al nassr');
INSERT INTO `Club` (`Name`) VALUES('brentford');
INSERT INTO `Club` (`Name`) VALUES('birmingham city');
INSERT INTO `Club` (`Name`) VALUES('godoy cruz');
INSERT INTO `Club` (`Name`) VALUES('atiker konyaspor');
INSERT INTO `Club` (`Name`) VALUES('ado den haag');
INSERT INTO `Club` (`Name`) VALUES('1. fc heidenheim 1846');
INSERT INTO `Club` (`Name`) VALUES('ulsan hyundai horang-i');
INSERT INTO `Club` (`Name`) VALUES('foggia');
INSERT INTO `Club` (`Name`) VALUES('racing club de lens');
INSERT INTO `Club` (`Name`) VALUES('sheffield united');
INSERT INTO `Club` (`Name`) VALUES('ipswich town');
INSERT INTO `Club` (`Name`) VALUES('hjk helsinki');
INSERT INTO `Club` (`Name`) VALUES('fc lugano');
INSERT INTO `Club` (`Name`) VALUES('odense boldklub');
INSERT INTO `Club` (`Name`) VALUES('moreirense fc');
INSERT INTO `Club` (`Name`) VALUES('silkeborg if');
INSERT INTO `Club` (`Name`) VALUES('tondela');
INSERT INTO `Club` (`Name`) VALUES('fc admira wacker mödling');
INSERT INTO `Club` (`Name`) VALUES('ross county fc');
INSERT INTO `Club` (`Name`) VALUES('queens park rangers');
INSERT INTO `Club` (`Name`) VALUES('fc ural');
INSERT INTO `Club` (`Name`) VALUES('cork city');
INSERT INTO `Club` (`Name`) VALUES('fc sion');
INSERT INTO `Club` (`Name`) VALUES('pec zwolle');
INSERT INTO `Club` (`Name`) VALUES('cultural leonesa');
INSERT INTO `Club` (`Name`) VALUES('heracles almelo');
INSERT INTO `Club` (`Name`) VALUES('fc thun');
INSERT INTO `Club` (`Name`) VALUES('stevenage');
INSERT INTO `Club` (`Name`) VALUES('cádiz cf');
INSERT INTO `Club` (`Name`) VALUES('adelaide united');
INSERT INTO `Club` (`Name`) VALUES('cremona');
INSERT INTO `Club` (`Name`) VALUES('eintracht braunschweig');
INSERT INTO `Club` (`Name`) VALUES('ud almería');
INSERT INTO `Club` (`Name`) VALUES('ettifaq fc');
INSERT INTO `Club` (`Name`) VALUES('orlando pirates');
INSERT INTO `Club` (`Name`) VALUES('wisła płock');
INSERT INTO `Club` (`Name`) VALUES('sanfrecce hiroshima');
INSERT INTO `Club` (`Name`) VALUES('fc anzhi makhachkala');
INSERT INTO `Club` (`Name`) VALUES('estoril praia');
INSERT INTO `Club` (`Name`) VALUES('cf os belenenses');
INSERT INTO `Club` (`Name`) VALUES('boavista fc');
INSERT INTO `Club` (`Name`) VALUES('sangju sangmu fc');
INSERT INTO `Club` (`Name`) VALUES('venezia');
INSERT INTO `Club` (`Name`) VALUES('shimizu s-pulse');
INSERT INTO `Club` (`Name`) VALUES('aj auxerre');
INSERT INTO `Club` (`Name`) VALUES('once caldas');
INSERT INTO `Club` (`Name`) VALUES('corporación club deportivo tuluá');
INSERT INTO `Club` (`Name`) VALUES('defensa y justicia');
INSERT INTO `Club` (`Name`) VALUES('gwangju fc');
INSERT INTO `Club` (`Name`) VALUES('ad alcorcón');
INSERT INTO `Club` (`Name`) VALUES('valenciennes fc');
INSERT INTO `Club` (`Name`) VALUES('cd viñazur');
INSERT INTO `Club` (`Name`) VALUES('fc ska-khabarovsk');
INSERT INTO `Club` (`Name`) VALUES('f. santa maria da feira');
INSERT INTO `Club` (`Name`) VALUES('zagłębie lubin');
INSERT INTO `Club` (`Name`) VALUES('gimnasia y esgrima la plata');
INSERT INTO `Club` (`Name`) VALUES('korona kielce');
INSERT INTO `Club` (`Name`) VALUES('júbilo iwata');
INSERT INTO `Club` (`Name`) VALUES('fc carl zeiss jena');
INSERT INTO `Club` (`Name`) VALUES('real salt lake');
INSERT INTO `Club` (`Name`) VALUES('ifk göteborg');
INSERT INTO `Club` (`Name`) VALUES('aarhus gf');
INSERT INTO `Club` (`Name`) VALUES('club atlético talleres');
INSERT INTO `Club` (`Name`) VALUES('carpi');
INSERT INTO `Club` (`Name`) VALUES('f.c. tokyo');
INSERT INTO `Club` (`Name`) VALUES('unión de santa fe');
INSERT INTO `Club` (`Name`) VALUES('rionegro águilas');
INSERT INTO `Club` (`Name`) VALUES('morecambe');
INSERT INTO `Club` (`Name`) VALUES('millwall');
INSERT INTO `Club` (`Name`) VALUES('sporting charleroi');
INSERT INTO `Club` (`Name`) VALUES('heart of midlothian');
INSERT INTO `Club` (`Name`) VALUES('carlisle united');
INSERT INTO `Club` (`Name`) VALUES('blackpool');
INSERT INTO `Club` (`Name`) VALUES('lech poznań');
INSERT INTO `Club` (`Name`) VALUES('sporting lokeren');
INSERT INTO `Club` (`Name`) VALUES('bk häcken');
INSERT INTO `Club` (`Name`) VALUES('atlético tucumán');
INSERT INTO `Club` (`Name`) VALUES('dundee fc');
INSERT INTO `Club` (`Name`) VALUES('hibernian');
INSERT INTO `Club` (`Name`) VALUES('central coast mariners');
INSERT INTO `Club` (`Name`) VALUES('albacete bpie');
INSERT INTO `Club` (`Name`) VALUES('patronato');
INSERT INTO `Club` (`Name`) VALUES('fc lausanne-sport');
INSERT INTO `Club` (`Name`) VALUES('charlton athletic');
INSERT INTO `Club` (`Name`) VALUES('rochdale');
INSERT INTO `Club` (`Name`) VALUES('doncaster rovers');
INSERT INTO `Club` (`Name`) VALUES('fc hansa rostock');
INSERT INTO `Club` (`Name`) VALUES('yokohama f・marinos');
INSERT INTO `Club` (`Name`) VALUES('perugia');
INSERT INTO `Club` (`Name`) VALUES('sc fortuna köln');
INSERT INTO `Club` (`Name`) VALUES('la spezia');
INSERT INTO `Club` (`Name`) VALUES('gazélec football club ajaccio');
INSERT INTO `Club` (`Name`) VALUES('salerno');
INSERT INTO `Club` (`Name`) VALUES('if elfsborg');
INSERT INTO `Club` (`Name`) VALUES('oxford united');
INSERT INTO `Club` (`Name`) VALUES('śląsk wrocław');
INSERT INTO `Club` (`Name`) VALUES('vercelli');
INSERT INTO `Club` (`Name`) VALUES('molde fk');
INSERT INTO `Club` (`Name`) VALUES('novara');
INSERT INTO `Club` (`Name`) VALUES('tiburones rojos de veracruz');
INSERT INTO `Club` (`Name`) VALUES('dsc arminia bielefeld');
INSERT INTO `Club` (`Name`) VALUES('amkar perm');
INSERT INTO `Club` (`Name`) VALUES('aalborg bk');
INSERT INTO `Club` (`Name`) VALUES('fc barcelona “b”');
INSERT INTO `Club` (`Name`) VALUES('al batin');
INSERT INTO `Club` (`Name`) VALUES('alianza petrolera');
INSERT INTO `Club` (`Name`) VALUES('cd numancia');
INSERT INTO `Club` (`Name`) VALUES('deportivo pasto');
INSERT INTO `Club` (`Name`) VALUES('oldham athletic');
INSERT INTO `Club` (`Name`) VALUES('roda jc kerkrade');
INSERT INTO `Club` (`Name`) VALUES('jagiellonia białystok');
INSERT INTO `Club` (`Name`) VALUES('örebro sk');
INSERT INTO `Club` (`Name`) VALUES('newcastle jets');
INSERT INTO `Club` (`Name`) VALUES('hammarby if');
INSERT INTO `Club` (`Name`) VALUES('chiavari');
INSERT INTO `Club` (`Name`) VALUES('sønderjyske');
INSERT INTO `Club` (`Name`) VALUES('al fayha');
INSERT INTO `Club` (`Name`) VALUES('villa maipú');
INSERT INTO `Club` (`Name`) VALUES('lechia gdańsk');
INSERT INTO `Club` (`Name`) VALUES('avellino');
INSERT INTO `Club` (`Name`) VALUES('bruk-bet termalica nieciecza');
INSERT INTO `Club` (`Name`) VALUES('pohang steelers');
INSERT INTO `Club` (`Name`) VALUES('piast gliwice');
INSERT INTO `Club` (`Name`) VALUES('fc sochaux-montbéliard');
INSERT INTO `Club` (`Name`) VALUES('san martín');
INSERT INTO `Club` (`Name`) VALUES('sandefjord fotball');
INSERT INTO `Club` (`Name`) VALUES('sk brann');
INSERT INTO `Club` (`Name`) VALUES('omiya ardija');
INSERT INTO `Club` (`Name`) VALUES('cracovia');
INSERT INTO `Club` (`Name`) VALUES('us quevilly rouen métropole');
INSERT INTO `Club` (`Name`) VALUES('excelsior');
INSERT INTO `Club` (`Name`) VALUES('cf reus');
INSERT INTO `Club` (`Name`) VALUES('sv sandhausen');
INSERT INTO `Club` (`Name`) VALUES('jeju united fc');
INSERT INTO `Club` (`Name`) VALUES('vegalta sendai');
INSERT INTO `Club` (`Name`) VALUES('jeonnam dragons');
INSERT INTO `Club` (`Name`) VALUES('houston dynamo');
INSERT INTO `Club` (`Name`) VALUES('patriotas boyacá fc');
INSERT INTO `Club` (`Name`) VALUES('al shabab');
INSERT INTO `Club` (`Name`) VALUES('atlético huila');
INSERT INTO `Club` (`Name`) VALUES('sparta rotterdam');
INSERT INTO `Club` (`Name`) VALUES('gangwon fc');
INSERT INTO `Club` (`Name`) VALUES('southend united');
INSERT INTO `Club` (`Name`) VALUES('odds bk');
INSERT INTO `Club` (`Name`) VALUES('msv duisburg');
INSERT INTO `Club` (`Name`) VALUES('la berrichonne de châteauroux');
INSERT INTO `Club` (`Name`) VALUES('afc eskilstuna');
INSERT INTO `Club` (`Name`) VALUES('us orléans loiret football');
INSERT INTO `Club` (`Name`) VALUES('al raed');
INSERT INTO `Club` (`Name`) VALUES('club olimpo');
INSERT INTO `Club` (`Name`) VALUES('stade brestois 29');
INSERT INTO `Club` (`Name`) VALUES('atlético bucaramanga');
INSERT INTO `Club` (`Name`) VALUES('sv mattersburg');
INSERT INTO `Club` (`Name`) VALUES('clermont foot 63');
INSERT INTO `Club` (`Name`) VALUES('shamrock rovers');
INSERT INTO `Club` (`Name`) VALUES('burton albion');
INSERT INTO `Club` (`Name`) VALUES('sint-truidense vv');
INSERT INTO `Club` (`Name`) VALUES('arsenal de sarandí');
INSERT INTO `Club` (`Name`) VALUES('royal excel mouscron');
INSERT INTO `Club` (`Name`) VALUES('football bourg en bresse peronnas 01');
INSERT INTO `Club` (`Name`) VALUES('sevilla atlético');
INSERT INTO `Club` (`Name`) VALUES('lyngby bk');
INSERT INTO `Club` (`Name`) VALUES('gif sundsvall');
INSERT INTO `Club` (`Name`) VALUES('ascoli');
INSERT INTO `Club` (`Name`) VALUES('bury');
INSERT INTO `Club` (`Name`) VALUES('al fateh');
INSERT INTO `Club` (`Name`) VALUES('jaguares fútbol club');
INSERT INTO `Club` (`Name`) VALUES('scunthorpe united');
INSERT INTO `Club` (`Name`) VALUES('fc luzern');
INSERT INTO `Club` (`Name`) VALUES('tours football club');
INSERT INTO `Club` (`Name`) VALUES('ssv jahn regensburg');
INSERT INTO `Club` (`Name`) VALUES('chamois niortais football club');
INSERT INTO `Club` (`Name`) VALUES('scr altach');
INSERT INTO `Club` (`Name`) VALUES('vålerenga fotball');
INSERT INTO `Club` (`Name`) VALUES('cittadella');
INSERT INTO `Club` (`Name`) VALUES('sandecja nowy sącz');
INSERT INTO `Club` (`Name`) VALUES('barnsley');
INSERT INTO `Club` (`Name`) VALUES('karlsruher sc');
INSERT INTO `Club` (`Name`) VALUES('motherwell');
INSERT INTO `Club` (`Name`) VALUES('fc würzburger kickers');
INSERT INTO `Club` (`Name`) VALUES('hamilton academical fc');
INSERT INTO `Club` (`Name`) VALUES('stabæk fotball');
INSERT INTO `Club` (`Name`) VALUES('albirex niigata');
INSERT INTO `Club` (`Name`) VALUES('aalesunds fk');
INSERT INTO `Club` (`Name`) VALUES('vfl osnabrück');
INSERT INTO `Club` (`Name`) VALUES('sarpsborg 08 ff');
INSERT INTO `Club` (`Name`) VALUES('lorca fc');
INSERT INTO `Club` (`Name`) VALUES('östersunds fk');
INSERT INTO `Club` (`Name`) VALUES('grêmio');
INSERT INTO `Club` (`Name`) VALUES('bohemian fc');
INSERT INTO `Club` (`Name`) VALUES('ac horsens');
INSERT INTO `Club` (`Name`) VALUES('kilmarnock');
INSERT INTO `Club` (`Name`) VALUES('bradford city');
INSERT INTO `Club` (`Name`) VALUES('arka gdynia');
INSERT INTO `Club` (`Name`) VALUES('bristol rovers');
INSERT INTO `Club` (`Name`) VALUES('paris fc');
INSERT INTO `Club` (`Name`) VALUES('lillestrøm sk');
INSERT INTO `Club` (`Name`) VALUES('grimsby town');
INSERT INTO `Club` (`Name`) VALUES('cd everton de viña del mar');
INSERT INTO `Club` (`Name`) VALUES('lincoln city');
INSERT INTO `Club` (`Name`) VALUES('chemnitzer fc');
INSERT INTO `Club` (`Name`) VALUES('envigado fc');
INSERT INTO `Club` (`Name`) VALUES('vfl sportfreunde lotte');
INSERT INTO `Club` (`Name`) VALUES('1. fc magdeburg');
INSERT INTO `Club` (`Name`) VALUES('hobro ik');
INSERT INTO `Club` (`Name`) VALUES('nac breda');
INSERT INTO `Club` (`Name`) VALUES('afc wimbledon');
INSERT INTO `Club` (`Name`) VALUES('fleetwood town');
INSERT INTO `Club` (`Name`) VALUES('lask linz');
INSERT INTO `Club` (`Name`) VALUES('milton keynes dons');
INSERT INTO `Club` (`Name`) VALUES('ohod club');
INSERT INTO `Club` (`Name`) VALUES('fk haugesund');
INSERT INTO `Club` (`Name`) VALUES('sg sonnenhof großaspach');
INSERT INTO `Club` (`Name`) VALUES('crawley town');
INSERT INTO `Club` (`Name`) VALUES('club atlético temperley');
INSERT INTO `Club` (`Name`) VALUES('atlético mineiro');
INSERT INTO `Club` (`Name`) VALUES('skn st. pölten');
INSERT INTO `Club` (`Name`) VALUES('hallescher fc');
INSERT INTO `Club` (`Name`) VALUES('wolfsberger ac');
INSERT INTO `Club` (`Name`) VALUES('incheon united fc');
INSERT INTO `Club` (`Name`) VALUES('sogndal fotball');
INSERT INTO `Club` (`Name`) VALUES('swindon town');
INSERT INTO `Club` (`Name`) VALUES('ventforet kofu');
INSERT INTO `Club` (`Name`) VALUES('viking fk');
INSERT INTO `Club` (`Name`) VALUES('mansfield town');
INSERT INTO `Club` (`Name`) VALUES('fsv zwickau');
INSERT INTO `Club` (`Name`) VALUES('exeter city');
INSERT INTO `Club` (`Name`) VALUES('fc rot-weiß erfurt');
INSERT INTO `Club` (`Name`) VALUES('cambridge united');
INSERT INTO `Club` (`Name`) VALUES('jönköpings södra if');
INSERT INTO `Club` (`Name`) VALUES('partick thistle f.c.');
INSERT INTO `Club` (`Name`) VALUES('colchester united');
INSERT INTO `Club` (`Name`) VALUES('crewe alexandra');
INSERT INTO `Club` (`Name`) VALUES('sw werder bremen ii');
INSERT INTO `Club` (`Name`) VALUES('górnik zabrze');
INSERT INTO `Club` (`Name`) VALUES('kristiansund bk');
INSERT INTO `Club` (`Name`) VALUES('fc helsingør');
INSERT INTO `Club` (`Name`) VALUES('sligo rovers');
INSERT INTO `Club` (`Name`) VALUES('gillingham');
INSERT INTO `Club` (`Name`) VALUES('forest green rovers');
INSERT INTO `Club` (`Name`) VALUES('yeovil town');
INSERT INTO `Club` (`Name`) VALUES('dundalk');
INSERT INTO `Club` (`Name`) VALUES('cd palestino');
INSERT INTO `Club` (`Name`) VALUES('barnet');
INSERT INTO `Club` (`Name`) VALUES('port vale');
INSERT INTO `Club` (`Name`) VALUES('halmstads bk');
INSERT INTO `Club` (`Name`) VALUES('newport county');
INSERT INTO `Club` (`Name`) VALUES('unión española');
INSERT INTO `Club` (`Name`) VALUES('finn harps');
INSERT INTO `Club` (`Name`) VALUES('bray wanderers');
INSERT INTO `Club` (`Name`) VALUES('derry city');
INSERT INTO `Club` (`Name`) VALUES('drogheda united');
INSERT INTO `Club` (`Name`) VALUES('limerick fc');
INSERT INTO `Club` (`Name`) VALUES('galway united');
INSERT INTO `Club` (`Name`) VALUES('são paulo');