INSERT INTO `Country` (`Name`) VALUES('portugal');
INSERT INTO `Country` (`Name`) VALUES('uruguay');
INSERT INTO `Country` (`Name`) VALUES('belgium');
INSERT INTO `Country` (`Name`) VALUES('brazil');
INSERT INTO `Country` (`Name`) VALUES('italy');
INSERT INTO `Country` (`Name`) VALUES('argentina');
INSERT INTO `Country` (`Name`) VALUES('france');
INSERT INTO `Country` (`Name`) VALUES('egypt');
INSERT INTO `Country` (`Name`) VALUES('spain');
INSERT INTO `Country` (`Name`) VALUES('poland');
INSERT INTO `Country` (`Name`) VALUES('chile');
INSERT INTO `Country` (`Name`) VALUES('croatia');
INSERT INTO `Country` (`Name`) VALUES('germany');
INSERT INTO `Country` (`Name`) VALUES('sweden');
INSERT INTO `Country` (`Name`) VALUES('england');
INSERT INTO `Country` (`Name`) VALUES('slovenia');
INSERT INTO `Country` (`Name`) VALUES('denmark');
INSERT INTO `Country` (`Name`) VALUES('colombia');
INSERT INTO `Country` (`Name`) VALUES('serbia');
INSERT INTO `Country` (`Name`) VALUES('russia');
INSERT INTO `Country` (`Name`) VALUES('holland');
INSERT INTO `Country` (`Name`) VALUES('senegal');
INSERT INTO `Country` (`Name`) VALUES('wales');
INSERT INTO `Country` (`Name`) VALUES('morocco');
INSERT INTO `Country` (`Name`) VALUES('korea republic');
INSERT INTO `Country` (`Name`) VALUES('united states');
INSERT INTO `Country` (`Name`) VALUES('slovakia');
INSERT INTO `Country` (`Name`) VALUES('guinea');
INSERT INTO `Country` (`Name`) VALUES('bosnia and herzegovina');
INSERT INTO `Country` (`Name`) VALUES('finland');
INSERT INTO `Country` (`Name`) VALUES('jamaica');
INSERT INTO `Country` (`Name`) VALUES('turkey');
INSERT INTO `Country` (`Name`) VALUES('ecuador');
INSERT INTO `Country` (`Name`) VALUES('greece');
INSERT INTO `Country` (`Name`) VALUES('cameroon');
INSERT INTO `Country` (`Name`) VALUES('ukraine');
INSERT INTO `Country` (`Name`) VALUES('romania');
INSERT INTO `Country` (`Name`) VALUES('czech republic');
INSERT INTO `Country` (`Name`) VALUES('gabon');
INSERT INTO `Country` (`Name`) VALUES('algeria');
INSERT INTO `Country` (`Name`) VALUES('japan');
INSERT INTO `Country` (`Name`) VALUES('cape verde islands');
INSERT INTO `Country` (`Name`) VALUES('mexico');
INSERT INTO `Country` (`Name`) VALUES('nigeria');
INSERT INTO `Country` (`Name`) VALUES('costa rica');
INSERT INTO `Country` (`Name`) VALUES('dominican republic');
INSERT INTO `Country` (`Name`) VALUES('mali');
INSERT INTO `Country` (`Name`) VALUES('iran');
INSERT INTO `Country` (`Name`) VALUES('togo');
INSERT INTO `Country` (`Name`) VALUES('switzerland');
INSERT INTO `Country` (`Name`) VALUES('peru');
INSERT INTO `Country` (`Name`) VALUES('austria');
INSERT INTO `Country` (`Name`) VALUES('israel');
INSERT INTO `Country` (`Name`) VALUES('iceland');
INSERT INTO `Country` (`Name`) VALUES('ghana');
INSERT INTO `Country` (`Name`) VALUES('scotland');
INSERT INTO `Country` (`Name`) VALUES('armenia');
INSERT INTO `Country` (`Name`) VALUES('saudi arabia');
INSERT INTO `Country` (`Name`) VALUES('syria');
INSERT INTO `Country` (`Name`) VALUES('venezuela');
INSERT INTO `Country` (`Name`) VALUES('northern ireland');
INSERT INTO `Country` (`Name`) VALUES('congo dr');
INSERT INTO `Country` (`Name`) VALUES('norway');
INSERT INTO `Country` (`Name`) VALUES('montenegro');
INSERT INTO `Country` (`Name`) VALUES('burkina faso');
INSERT INTO `Country` (`Name`) VALUES('zimbabwe');
INSERT INTO `Country` (`Name`) VALUES('canada');
INSERT INTO `Country` (`Name`) VALUES('republic of ireland');
INSERT INTO `Country` (`Name`) VALUES('albania');
INSERT INTO `Country` (`Name`) VALUES('kenya');
INSERT INTO `Country` (`Name`) VALUES('new zealand');
INSERT INTO `Country` (`Name`) VALUES('paraguay');
INSERT INTO `Country` (`Name`) VALUES('tunisia');
INSERT INTO `Country` (`Name`) VALUES('south africa');
INSERT INTO `Country` (`Name`) VALUES('georgia');
INSERT INTO `Country` (`Name`) VALUES('australia');
INSERT INTO `Country` (`Name`) VALUES('uzbekistan');
INSERT INTO `Country` (`Name`) VALUES('kosovo');
INSERT INTO `Country` (`Name`) VALUES('mozambique');
INSERT INTO `Country` (`Name`) VALUES('hungary');
INSERT INTO `Country` (`Name`) VALUES('estonia');
INSERT INTO `Country` (`Name`) VALUES('cuba');
INSERT INTO `Country` (`Name`) VALUES('panama');
INSERT INTO `Country` (`Name`) VALUES('bulgaria');
INSERT INTO `Country` (`Name`) VALUES('angola');
INSERT INTO `Country` (`Name`) VALUES('sudan');
INSERT INTO `Country` (`Name`) VALUES('fyr macedonia');
INSERT INTO `Country` (`Name`) VALUES('gibraltar');
INSERT INTO `Country` (`Name`) VALUES('lithuania');
INSERT INTO `Country` (`Name`) VALUES('benin');
INSERT INTO `Country` (`Name`) VALUES('belarus');
INSERT INTO `Country` (`Name`) VALUES('moldova');
INSERT INTO `Country` (`Name`) VALUES('congo');
INSERT INTO `Country` (`Name`) VALUES('sierra leone');
INSERT INTO `Country` (`Name`) VALUES('curaçao');
INSERT INTO `Country` (`Name`) VALUES('honduras');
INSERT INTO `Country` (`Name`) VALUES('iraq');
INSERT INTO `Country` (`Name`) VALUES('guinea-bissau');
INSERT INTO `Country` (`Name`) VALUES('trinidad and tobago');
INSERT INTO `Country` (`Name`) VALUES('gambia');
INSERT INTO `Country` (`Name`) VALUES('chad');
INSERT INTO `Country` (`Name`) VALUES('tanzania');
INSERT INTO `Country` (`Name`) VALUES('cyprus');
INSERT INTO `Country` (`Name`) VALUES('niger');
INSERT INTO `Country` (`Name`) VALUES('liechtenstein');
INSERT INTO `Country` (`Name`) VALUES('oman');
INSERT INTO `Country` (`Name`) VALUES('haiti');
INSERT INTO `Country` (`Name`) VALUES('latvia');
INSERT INTO `Country` (`Name`) VALUES('zambia');
INSERT INTO `Country` (`Name`) VALUES('guatemala');
INSERT INTO `Country` (`Name`) VALUES('equatorial guinea');
INSERT INTO `Country` (`Name`) VALUES('korea dpr');
INSERT INTO `Country` (`Name`) VALUES('madagascar');
INSERT INTO `Country` (`Name`) VALUES('new caledonia');
INSERT INTO `Country` (`Name`) VALUES('eritrea');
INSERT INTO `Country` (`Name`) VALUES('bermuda');
INSERT INTO `Country` (`Name`) VALUES('libya');
INSERT INTO `Country` (`Name`) VALUES('luxembourg');
INSERT INTO `Country` (`Name`) VALUES('kuwait');
INSERT INTO `Country` (`Name`) VALUES('uganda');
INSERT INTO `Country` (`Name`) VALUES('palestine');
INSERT INTO `Country` (`Name`) VALUES('comoros');
INSERT INTO `Country` (`Name`) VALUES('suriname');
INSERT INTO `Country` (`Name`) VALUES('mauritania');
INSERT INTO `Country` (`Name`) VALUES('st. kitts and nevis');
INSERT INTO `Country` (`Name`) VALUES('azerbaijan');
INSERT INTO `Country` (`Name`) VALUES('el salvador');
INSERT INTO `Country` (`Name`) VALUES('central african republic');
INSERT INTO `Country` (`Name`) VALUES('fiji');
INSERT INTO `Country` (`Name`) VALUES('somalia');
INSERT INTO `Country` (`Name`) VALUES('guam');
INSERT INTO `Country` (`Name`) VALUES('philippines');
INSERT INTO `Country` (`Name`) VALUES('kazakhstan');
INSERT INTO `Country` (`Name`) VALUES('china pr');
INSERT INTO `Country` (`Name`) VALUES('qatar');
INSERT INTO `Country` (`Name`) VALUES('ethiopia');
INSERT INTO `Country` (`Name`) VALUES('bolivia');
INSERT INTO `Country` (`Name`) VALUES('mauritius');
INSERT INTO `Country` (`Name`) VALUES('montserrat');
INSERT INTO `Country` (`Name`) VALUES('liberia');
INSERT INTO `Country` (`Name`) VALUES('puerto rico');
INSERT INTO `Country` (`Name`) VALUES('faroe islands');
INSERT INTO `Country` (`Name`) VALUES('lebanon');
INSERT INTO `Country` (`Name`) VALUES('namibia');
INSERT INTO `Country` (`Name`) VALUES('barbados');
INSERT INTO `Country` (`Name`) VALUES('guyana');
INSERT INTO `Country` (`Name`) VALUES('antigua and barbuda');
INSERT INTO `Country` (`Name`) VALUES('thailand');
INSERT INTO `Country` (`Name`) VALUES('burundi');
INSERT INTO `Country` (`Name`) VALUES('turkmenistan');
INSERT INTO `Country` (`Name`) VALUES('belize');
INSERT INTO `Country` (`Name`) VALUES('malta');
INSERT INTO `Country` (`Name`) VALUES('st. lucia');
INSERT INTO `Country` (`Name`) VALUES('vietnam');
INSERT INTO `Country` (`Name`) VALUES('afghanistan');
INSERT INTO `Country` (`Name`) VALUES('sri lanka');
INSERT INTO `Country` (`Name`) VALUES('kyrgyzstan');
INSERT INTO `Country` (`Name`) VALUES('brunei darussalam');
INSERT INTO `Country` (`Name`) VALUES('san marino');
INSERT INTO `Country` (`Name`) VALUES('hong kong');