INSERT INTO `League` (`Name`) VALUES('laliga santander');
INSERT INTO `League` (`Name`) VALUES('premier league');
INSERT INTO `League` (`Name`) VALUES('icons');
INSERT INTO `League` (`Name`) VALUES('calcio a');
INSERT INTO `League` (`Name`) VALUES('ligue 1 conforama');
INSERT INTO `League` (`Name`) VALUES('bundesliga');
INSERT INTO `League` (`Name`) VALUES('liga nos');
INSERT INTO `League` (`Name`) VALUES('primera división');
INSERT INTO `League` (`Name`) VALUES('efl championship');
INSERT INTO `League` (`Name`) VALUES('eredivisie');
INSERT INTO `League` (`Name`) VALUES('russian football premier league');
INSERT INTO `League` (`Name`) VALUES('major league soccer');
INSERT INTO `League` (`Name`) VALUES('belgium pro league');
INSERT INTO `League` (`Name`) VALUES('ukrayina liha');
INSERT INTO `League` (`Name`) VALUES('süper lig');
INSERT INTO `League` (`Name`) VALUES('alka superliga');
INSERT INTO `League` (`Name`) VALUES('liga bancomer mx');
INSERT INTO `League` (`Name`) VALUES('meiji yasuda j1 league');
INSERT INTO `League` (`Name`) VALUES('raiffeisen super league');
INSERT INTO `League` (`Name`) VALUES('österreichische fußball-bundesliga');
INSERT INTO `League` (`Name`) VALUES('k league classic');
INSERT INTO `League` (`Name`) VALUES('dawry jameel');
INSERT INTO `League` (`Name`) VALUES('hellas liga');
INSERT INTO `League` (`Name`) VALUES('hyundai a-league');
INSERT INTO `League` (`Name`) VALUES('efl league one');
INSERT INTO `League` (`Name`) VALUES('domino’s ligue 2');
INSERT INTO `League` (`Name`) VALUES('scottish premiership');
INSERT INTO `League` (`Name`) VALUES('calcio b');
INSERT INTO `League` (`Name`) VALUES('ekstraklasa');
INSERT INTO `League` (`Name`) VALUES('eliteserien');
INSERT INTO `League` (`Name`) VALUES('laliga 1 i 2 i 3');
INSERT INTO `League` (`Name`) VALUES('liga dimayor');
INSERT INTO `League` (`Name`) VALUES('south african fl');
INSERT INTO `League` (`Name`) VALUES('bundesliga 2');
INSERT INTO `League` (`Name`) VALUES('3. liga');
INSERT INTO `League` (`Name`) VALUES('allsvenskan');
INSERT INTO `League` (`Name`) VALUES('efl league two');
INSERT INTO `League` (`Name`) VALUES('česká liga');
INSERT INTO `League` (`Name`) VALUES('campeonato scotiabank');
INSERT INTO `League` (`Name`) VALUES('finnliiga');
INSERT INTO `League` (`Name`) VALUES('sse airtricity league');